---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: share
    run_list:
      - recipe[storj::share]
    attributes:
  - name: bridge
    run_list:
      - recipe[storj::bridges]
      - recipe[storj::landlord]
    attributes:
  - name: renters
    run_list:
      - recipe[storj::renters]
    attributes:
  - name: bridge_proxy
    run_list:
      - recipe[storj::bridge_proxy]
    attributes:
